# Exploratory Data Analysis on Global Terrorism Dataset
**By: ``Suraj Honkamble``.**
### Intermediate Task-1

### Tableau Dashboard Link: https://public.tableau.com/app/profile/suraj.honkamble/viz/TerroristHostspotDetectionDashboard/Dashboard

#### Note: For making changes like filling Nan values or replace some values I took help from https://www.start.umd.edu/gtd/downloads/Codebook.pdf this Source.

### Import Required libraries

In [1]:
import pandas as pd
import numpy as np

### Read the Data

In [2]:
pd.options.display.max_columns=200

**Dataset link: https://drive.google.com/file/d/1luTU7xBvI7QAGPbQMxEHcgKUi9d6UeP_/view**

In [3]:
data=pd.read_csv("D:\\DATA SCIENCE Internship with LGMVIP\\data\\globalterrorism.csv", encoding='latin1')
data.head()

C:\Users\User\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (4,6,31,33,61,62,63,76,79,90,92,94,96,114,115,121) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


eventid  iyear  imonth  iday approxdate  extended resolution  country  \
0  197000000001   1970       7     2        NaN         0        NaN       58   
1  197000000002   1970       0     0        NaN         0        NaN      130   
2  197001000001   1970       1     0        NaN         0        NaN      160   
3  197001000002   1970       1     0        NaN         0        NaN       78   
4  197001000003   1970       1     0        NaN         0        NaN      101   

          country_txt  region                   region_txt provstate  \
0  Dominican Republic       2  Central America & Caribbean       NaN   
1              Mexico       1                North America   Federal   
2         Philippines       5               Southeast Asia    Tarlac   
3              Greece       8               Western Europe    Attica   
4               Japan       4                    East Asia   Fukouka   

            city   latitude   longitude  specificity  vicinity location  \
0  Santo Domingo  18.456792  -69.951164          1.0         0      NaN   
1    Mexico city  19.371887  -99.086624          1.0         0      NaN   
2        Unknown  15.478598  120.599741          4.0         0      NaN   
3         Athens  37.997490   23.762728          1.0         0      NaN   
4        Fukouka  33.580412  130.396361          1.0         0      NaN   

  summary  crit1  crit2  crit3  doubtterr  alternative alternative_txt  \
0     NaN      1      1      1        0.0          NaN             NaN   
1     NaN      1      1      1        0.0          NaN             NaN   
2     NaN      1      1      1        0.0          NaN             NaN   
3     NaN      1      1      1        0.0          NaN             NaN   
4     NaN      1      1      1       -9.0          NaN             NaN   

   multiple  success  suicide  attacktype1                 attacktype1_txt  \
0       0.0        1        0            1                   Assassination   
1       0.0        1        0            6     Hostage Taking (Kidnapping)   
2       0.0        1        0            1                   Assassination   
3       0.0        1        0            3               Bombing/Explosion   
4       0.0        1        0            7  Facility/Infrastructure Attack   

   attacktype2 attacktype2_txt  attacktype3 attacktype3_txt  targtype1  \
0          NaN             NaN          NaN             NaN         14   
1          NaN             NaN          NaN             NaN          7   
2          NaN             NaN          NaN             NaN         10   
3          NaN             NaN          NaN             NaN          7   
4          NaN             NaN          NaN             NaN          7   

                 targtype1_txt  targsubtype1  \
0  Private Citizens & Property          68.0   
1      Government (Diplomatic)          45.0   
2          Journalists & Media          54.0   
3      Government (Diplomatic)          46.0   
4      Government (Diplomatic)          46.0   

                                    targsubtype1_txt  \
0                                     Named Civilian   
1  Diplomatic Personnel (outside of embassy, cons...   
2                    Radio Journalist/Staff/Facility   
3                                  Embassy/Consulate   
4                                  Embassy/Consulate   

                         corp1                  target1  natlty1  \
0                          NaN             Julio Guzman     58.0   
1  Belgian Ambassador Daughter  Nadine Chaval, daughter     21.0   
2             Voice of America                 Employee    217.0   
3                          NaN             U.S. Embassy    217.0   
4                          NaN           U.S. Consulate    217.0   

          natlty1_txt  targtype2 targtype2_txt  targsubtype2 targsubtype2_txt  \
0  Dominican Republic        NaN           NaN           NaN              NaN   
1             Belgium        NaN           NaN           NaN              NaN   


In [4]:
df=data.copy()

#### Column Information go here : https://www.kaggle.com/datasets/START-UMD/gtd

In [5]:
df.shape

(181691, 135)

### Missing values

In [6]:
missing_val_in_col=[]
for col in df.columns:
    if df[col].isna().sum()!=0:
        missing_val_in_col.append(col)
print(missing_val_in_col)

['approxdate', 'resolution', 'provstate', 'city', 'latitude', 'longitude', 'specificity', 'location', 'summary', 'doubtterr', 'alternative', 'alternative_txt', 'multiple', 'attacktype2', 'attacktype2_txt', 'attacktype3', 'attacktype3_txt', 'targsubtype1', 'targsubtype1_txt', 'corp1', 'target1', 'natlty1', 'natlty1_txt', 'targtype2', 'targtype2_txt', 'targsubtype2', 'targsubtype2_txt', 'corp2', 'target2', 'natlty2', 'natlty2_txt', 'targtype3', 'targtype3_txt', 'targsubtype3', 'targsubtype3_txt', 'corp3', 'target3', 'natlty3', 'natlty3_txt', 'gsubname', 'gname2', 'gsubname2', 'gname3', 'gsubname3', 'motive', 'guncertain1', 'guncertain2', 'guncertain3', 'nperps', 'nperpcap', 'claimed', 'claimmode', 'claimmode_txt', 'claim2', 'claimmode2', 'claimmode2_txt', 'claim3', 'claimmode3', 'claimmode3_txt', 'compclaim', 'weapsubtype1', 'weapsubtype1_txt', 'weaptype2', 'weaptype2_txt', 'weapsubtype2', 'weapsubtype2_txt', 'weaptype3', 'weaptype3_txt', 'weapsubtype3', 'weapsubtype3_txt', 'weaptype4', 

#### Above are the column list which contains missing values.

### Drop the columns which has more than 100000 missing values

In [7]:
nan_percent=df.isnull().sum()*100/len(df)
nan_percent.sort_values(ascending = False)

gsubname3           99.988992
weapsubtype4_txt    99.961473
weapsubtype4        99.961473
weaptype4           99.959822
weaptype4_txt       99.959822
                      ...    
suicide              0.000000
success              0.000000
crit3                0.000000
property             0.000000
eventid              0.000000
Length: 135, dtype: float64

In [8]:
columns_to_drop = nan_percent[nan_percent.values>45].index
df.drop(columns_to_drop, axis=1, inplace=True)
df.columns

Index(['eventid', 'iyear', 'imonth', 'iday', 'extended', 'country',
       'country_txt', 'region', 'region_txt', 'provstate', 'city', 'latitude',
       'longitude', 'specificity', 'vicinity', 'summary', 'crit1', 'crit2',
       'crit3', 'doubtterr', 'multiple', 'success', 'suicide', 'attacktype1',
       'attacktype1_txt', 'targtype1', 'targtype1_txt', 'targsubtype1',
       'targsubtype1_txt', 'corp1', 'target1', 'natlty1', 'natlty1_txt',
       'gname', 'guncertain1', 'individual', 'nperps', 'nperpcap', 'claimed',
       'weaptype1', 'weaptype1_txt', 'weapsubtype1', 'weapsubtype1_txt',
       'weapdetail', 'nkill', 'nkillus', 'nkillter', 'nwound', 'nwoundus',
       'nwoundte', 'property', 'ishostkid', 'scite1', 'dbsource', 'INT_LOG',
       'INT_IDEO', 'INT_MISC', 'INT_ANY'],
      dtype='object')

In [9]:
df.shape

(181691, 58)

## Data Cleaning

### Duplicate data

In [10]:
df.duplicated().sum()

0

### From column "iyear, imonth, iday" create Date column

In [11]:
df['imonth'].unique()

array([ 7,  0,  1,  2,  3,  4,  5,  6,  8,  9, 10, 11, 12], dtype=int64)

**Month cannot be 0, replace 0 with 1.**

In [12]:
df['imonth'].replace({0:1}, inplace=True)
df['imonth'].unique()

array([ 7,  1,  2,  3,  4,  5,  6,  8,  9, 10, 11, 12], dtype=int64)

In [13]:
df['iday'].unique()

array([ 2,  0,  1,  3,  6,  8,  9, 10, 11, 12, 13, 14, 15, 19, 20, 21, 22,
       25, 26, 27, 28, 30, 31,  4,  7, 16, 17, 18, 23, 24,  5, 29],
      dtype=int64)

**Day cannot be 0, replace 0 with 1.**

In [14]:
df['iday'].replace({0:1}, inplace=True)
df['iday'].unique()

array([ 2,  1,  3,  6,  8,  9, 10, 11, 12, 13, 14, 15, 19, 20, 21, 22, 25,
       26, 27, 28, 30, 31,  4,  7, 16, 17, 18, 23, 24,  5, 29],
      dtype=int64)

In [15]:
df['iyear']=df['iyear'].astype(str)
df['imonth']=df['imonth'].astype(str)
df['iday']=df['iday'].astype(str)

In [16]:
df['date']=df['iyear'] + "-" + df['imonth'] +"-"+ df['iday']
df['date']=pd.to_datetime(df['date'])
df['date']

0        1970-07-02
1        1970-01-01
2        1970-01-01
3        1970-01-01
4        1970-01-01
            ...    
181686   2017-12-31
181687   2017-12-31
181688   2017-12-31
181689   2017-12-31
181690   2017-12-31
Name: date, Length: 181691, dtype: datetime64[ns]

### Drop incident date related column

In [17]:
df.drop(['iyear','imonth','iday'], axis=1, inplace=True)

### Analyze extended column
- 1 = "Yes" The duration of an incident extended more than 24 hours. 0 = "No" The duration of an incident extended less

#### Rename this column as Duration of incident, and replace 1 with ">24hrs", and 0 with "<24hrs"

In [18]:
df.rename({'extended':'incident_duration'}, axis=1, inplace=True)
df['incident_duration'].replace({1:">24hrs",0:"<24hrs"}, inplace=True)
df['incident_duration'].unique()

array(['<24hrs', '>24hrs'], dtype=object)

### Drop columns country and region becuase we already have country name and region name in another column

In [19]:
df.drop(['country','region'], axis=1, inplace=True)
df.rename({'country_txt':'country','region_txt':'region'}, axis=1, inplace=True)

### Drop provstate column as it contains many Nan.. we have city column so no need of province state

In [20]:
df.drop('provstate', axis=1, inplace=True)

### Drop those rows which do not have latitude or longitude.. This step is ecessary because Tableau Map understand latitude and longitude.

### Rename Columns

In [21]:
df.rename({'attacktype1_txt': 'attack_type', 'targtype1_txt': 'target_type', 'targsubtype1_txt': 'target_subtype','target1': 'target', 'natlty1_txt': 'nationality','weaptype1_txt': 'weapon_type'}, axis=1, inplace=True)

### Drop unwanted column

In [22]:
df.drop(['attacktype1', 'targtype1', 'targsubtype1', 'summary', 'target_subtype','guncertain1','scite1','dbsource',
         'natlty1', 'weaptype1', 'weapsubtype1', 'weapdetail','ishostkid','INT_LOG','INT_IDEO','INT_MISC','INT_ANY',
         'weapsubtype1_txt','crit1', 'crit2', 'crit3','doubtterr'], axis=1, inplace=True)

### Analyze specificity column
- We already the vicinity of attack so drop specificity column

In [23]:
df['specificity'].unique()

array([ 1.,  4.,  5.,  2.,  3., nan])

In [24]:
df.drop('specificity', axis=1, inplace=True)

### Analyze vicinity
- 1 = "Yes" The incident occurred in the immediate vicinity of the city in question. 
- 0 = "No" The incident in the city itself

In [25]:
df['vicinity'].unique()

array([ 0,  1, -9], dtype=int64)

#### Replace -9 with 0

In [26]:
df['vicinity'].replace({-9:0}, inplace=True)

In [27]:
df['vicinity'].replace({0:'In City', 1:'Near City'}, inplace=True)

### Rename corp1 

In [28]:
df.rename({'corp1':'targeted_corporate'}, axis=1, inplace=True)

### Rename gname to Perpetrator Group Name

In [29]:
df.rename({'gname':'terrorist_group'}, axis=1, inplace=True)

### Rename individual columns

In [30]:
df.rename({'individual':'terrorist_group_size'}, axis=1, inplace=True)
df['terrorist_group_size'].replace({0:'individual',1:'group'}, inplace=True)

### Rename nperps

In [31]:
df.rename({'nperps':'number_of_terrorist'}, axis=1, inplace=True)

### Rename nperpcap

In [32]:
df.rename({'nperpcap':'number_of_terrorist_captured'}, axis=1, inplace=True)

### Rename claimed

In [33]:
df.rename({'claimed':'attack_claimed'}, axis=1, inplace=True)
df['attack_claimed'].replace({0:'No',1:'Yes'}, inplace=True)

### Rename nkill, nkillsus, nkillter, nwound, nwoundus, nwoundte

In [34]:
df.rename({'nkill':'number_of_kills'}, axis=1, inplace=True)
df.rename({'nkillus':'number_of_kills_in_US'}, axis=1, inplace=True)
df.rename({'nkillter':'number_of_terrorist_died'}, axis=1, inplace=True)
df.rename({'nwound':'number_of_injured'}, axis=1, inplace=True)
df.rename({'nwoundus':'number_of_injured_in_US'}, axis=1, inplace=True)
df.rename({'nwoundte':'number_of_injured_terrorist'}, axis=1, inplace=True)

### Rename property

In [35]:
df.rename({'property':'property_damaged'}, axis=1, inplace=True)
df['property_damaged'].replace({0:'No',1:'Yes'}, inplace=True)

### Renale multiple

In [36]:
df.rename({'multiple':'multiple_attack'}, axis=1, inplace=True)
df['multiple_attack'].replace({0:'No',1:'Yes'}, inplace=True)

### Rename success

In [37]:
df.rename({'success':'success_attack'}, axis=1, inplace=True)
df['success_attack'].replace({0:'No',1:'Yes'}, inplace=True)

### Rename suicide

In [38]:
#df.rename({'suicide':'suicide_attack'}, axis=1, inplace=True)
#df['suicide_attack'].replace({0:'No',1:'Yes'}, inplace=True)

### Missing values

In [39]:
df.isna().sum()

eventid                             0
incident_duration                   0
country                             0
region                              0
city                              434
latitude                         4556
longitude                        4557
vicinity                            0
multiple_attack                     1
success_attack                      0
suicide_attack                      0
attack_type                         0
target_type                         0
targeted_corporate              42550
target                            636
nationality                      1559
terrorist_group                     0
terrorist_group_size                0
number_of_terrorist             71115
number_of_terrorist_captured    69489
attack_claimed                  66120
weapon_type                         0
number_of_kills                 10313
number_of_kills_in_US           64446
number_of_terrorist_died        66958
number_of_injured               16311
number_of_in

In [40]:
df.dropna(inplace=True)

In [41]:
df.shape

(81668, 30)

In [42]:
df.isna().sum()

eventid                         0
incident_duration               0
country                         0
region                          0
city                            0
latitude                        0
longitude                       0
vicinity                        0
multiple_attack                 0
success_attack                  0
suicide_attack                  0
attack_type                     0
target_type                     0
targeted_corporate              0
target                          0
nationality                     0
terrorist_group                 0
terrorist_group_size            0
number_of_terrorist             0
number_of_terrorist_captured    0
attack_claimed                  0
weapon_type                     0
number_of_kills                 0
number_of_kills_in_US           0
number_of_terrorist_died        0
number_of_injured               0
number_of_injured_in_US         0
number_of_injured_terrorist     0
property_damaged                0
date          

In [44]:
df.dtypes

eventid                                  int64
incident_duration                       object
country                                 object
region                                  object
city                                    object
latitude                               float64
longitude                              float64
vicinity                                object
multiple_attack                         object
success_attack                          object
suicide_attack                          object
attack_type                             object
target_type                             object
targeted_corporate                      object
target                                  object
nationality                             object
terrorist_group                         object
terrorist_group_size                    object
number_of_terrorist                    float64
number_of_terrorist_captured           float64
attack_claimed                          object
weapon_type  

### Replacing SOme values in columns

In [55]:
for col in df.columns:
    if df[col].dtype=='object':
        print(col, df[col].nunique(), df[col].unique())
        print("**"*10)

incident_duration 2 ['<24hrs' '>24hrs']
********************
country 163 ['United States' 'Poland' 'United Kingdom' 'Italy' 'France' 'Switzerland'
 'Israel' 'Austria' 'Belgium' 'Brunei' 'Zaire' 'Argentina'
 "People's Republic of the Congo" 'Jordan' 'Cambodia' 'Australia'
 'Portugal' 'India' 'Sri Lanka' 'Netherlands' 'Nigeria' 'Guyana' 'Sweden'
 'Bangladesh' 'New Zealand' 'Lebanon' 'Spain' 'Canada' 'Philippines'
 'Azerbaijan' 'Algeria' 'South Africa' 'Turkey' 'Germany' 'Uganda'
 'Ethiopia' 'Malta' 'Pakistan' 'West Bank and Gaza Strip' 'Peru'
 'Thailand' 'Egypt' 'Rwanda' 'Colombia' 'Bulgaria' 'Yemen' 'Russia'
 'Georgia' 'Iran' 'Yugoslavia' 'Sierra Leone' 'Indonesia' 'Iraq' 'Nepal'
 'Paraguay' 'Sudan' 'Uzbekistan' 'Zambia' 'Greece' 'Mozambique' 'Kosovo'
 'Angola' 'Ukraine' 'Venezuela' 'Kyrgyzstan' 'Haiti' 'Tajikistan'
 'Guatemala' 'Albania' 'Bosnia-Herzegovina' 'Japan' 'Burundi' 'Macedonia'
 'Mexico' 'Afghanistan' 'Ecuador' 'Belize' 'East Timor' 'Nicaragua'
 'Malaysia' 'Croatia' 'Latvia' 

#### In column attack_claimed and property_damaged, -9 is a value which indicated unknown.. replace it by unknown

In [58]:
df['attack_claimed'].replace({-9.0:'Unknown'}, inplace=True)
df['property_damaged'].replace({-9:'Unknown'}, inplace=True)
print(df['property_damaged'].unique())
print(df['attack_claimed'].unique())

['Yes' 'Unknown' 'No']
['No' 'Yes' 'Unknown']


In [59]:
df.columns

Index(['eventid', 'incident_duration', 'country', 'region', 'city', 'latitude',
       'longitude', 'vicinity', 'multiple_attack', 'success_attack',
       'suicide_attack', 'attack_type', 'target_type', 'targeted_corporate',
       'target', 'nationality', 'terrorist_group', 'terrorist_group_size',
       'number_of_terrorist', 'number_of_terrorist_captured', 'attack_claimed',
       'weapon_type', 'number_of_kills', 'number_of_kills_in_US',
       'number_of_terrorist_died', 'number_of_injured',
       'number_of_injured_in_US', 'number_of_injured_terrorist',
       'property_damaged', 'date'],
      dtype='object')

In [61]:
numerical=['number_of_kills', 'number_of_kills_in_US',
       'number_of_terrorist_died', 'number_of_injured',
       'number_of_injured_in_US', 'number_of_injured_terrorist',
        'number_of_terrorist_captured']

In [64]:
for col in numerical:
    print(col, df[col].unique())
    print("**"*10)

number_of_kills [  0.   2.   1.   3.   8.   4.   5.   6.   7.  12.  20.  11.  15.  23.
  10.  19.  18.  14.  81.  21.  13.   9.  25.  17.  96.  64.  30.  28.
  35.  29.  34.  50.  16.  22.  44.  31.  24.  60.  27.  26.  33.  57.
  59.  53.  40. 100.  47.  71.  58.  41.  70.  46. 110.  54.  77.  37.
  32.  36. 120.  92.  42.  74.  69.  79. 250. 141.  72.  38. 101.  39.
 134.  68.  56.  43. 102.  76.  51.  82. 115. 106.  48.  61.  52.  45.
  97. 103.  91.  62.  87. 287. 670.  49. 298.  67. 150.  75.  65. 122.
 158. 152.  86.  85. 121. 108. 105. 224.  93.  73.  83.  66.  88. 300.
  55.  63. 383. 154. 284. 190.  98. 130.  78. 230. 151. 127. 266. 163.
 200. 128. 588. 311.]
********************
number_of_kills_in_US [ 0.  2.  1.  3.  8.  5.  7. 15. 17. 38.  4. 20.  6. 13.  9. 10. 44.]
********************
number_of_terrorist_died [  0.   1.   2.   6.  80.   3.  20.  13.   4.   5.  10.  14.  15.   7.
  17.   9.  11.   8.  34.  30.  18.  19.  12.  26.  35.  32.  22.  16.
  40.  28.  25.  31.  

In [65]:
df['number_of_terrorist_captured'].replace({-99.:0}, inplace=True)
df['number_of_terrorist_captured'].unique()

array([  0. ,   1. ,   2. ,   4. ,   3. ,   5. ,   9. ,   7. ,   6. ,
        26. ,   8. ,  10. ,  14. ,  45. ,  12. ,   2.5,  25. ,  32. ,
        27. ,  -9. ,  43. ,  11. ,  21. ,  15. ,  50. ,  13. ,  28. ,
        16. ,  19. ,  24. ,  18. ,  20. , 126. ,  17. ,  55. ,  60. ,
        23. ,  22. ,  40. ,  63. ,  30. ])

### Save this Cleaned data to create tableau dashboard.

In [66]:
df.to_csv('D:\\DATA SCIENCE Internship with LGMVIP\\data\\globalterrorism_clean.csv', index=False)

### To see complete data analysis on Terrorist Hotspot detection go to Tableau link.

### Tableau Dashboard Link: https://public.tableau.com/app/profile/suraj.honkamble/viz/TerroristHostspotDetectionDashboard/Dashboard